- name: Install nginx
  apt:
    name: nginx
    state: latest

- name: Start nginx
  service:
    name: nginx
    enabled: yes

- name: Put nginx setting file
  template:
    src: etc/nginx/sites-available/default
    dest: /etc/nginx/sites-available/default
  notify:
    - restart nginx
